name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install the package
      run: npm install

    - name: Run the tests
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test

    - name: Run the tests
      if: runner.os != 'Linux'
      run: npm test
